export const USERS_REQUSET_LOADING = 'USERS_REQUSET_LOADING';
export const USERS_REQUSET_SUCCESS = 'USERS_REQUSET_SUCCESS';
export const USERS_REQUSET_ERROR = 'USERS_REQUSET_ERROR';

export const LOAD_USER_FROM_TOKEN = "LOAD_USER_FROM_TOKEN";
export const SET_LOGIN_USER = "SET_LOGIN_USER";
export const CLEAR_PREVIOUS_USER = "CLEAR_PREVIOUS_USER";

